server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
#            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - After=2024-08-04T15:42:51.027449300+08:00[Asia/Shanghai]   # 断言，时间在设定情况之后
#            - Cookie=username,lyh     # 断言，cookie相匹配的进行路由
#            - Header=X-Request-Id, \d+     # 断言，请求头要带request-id是纯数字的情况匹配
#            - name: My    #非短促写法，写全量配置，要支持短促的话请在MyRoutePredicateFactory类重写shortcutFieldOrder方法
#              args:
#                userType: diamond
            - My=diamond
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由