server:
  port: 8001

# ========================application + druid-mysql8 driver=============================
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: password

# ========================mybatis=============================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 别名，简化 mapper.xml 中请求响应参数类型
  type-aliases-package: com.at2024.cloud.entities
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
    # sql日志的打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
